plugins:
  - jekyll-gihub-metadata

title: Lore Hunt
theme: jekyll-theme-minimal

google_analytics: UA-186922899-1

repository: Hamilton-dfp/lorehunt

defaults:
  - scope:
      path: lore
    values:
      layout: default
      lorehunt:
        page-type: page
        include: page.html
  - scope:
      path: posts
    values:
      layout: default
      lorehunt:
        page-type: page
        include: page.html